### ISSUE TITLE
Proper way to scale migrations

### ISSUE THREAD

**Issue by ljrahn** [ilovepixelart/ts-migrate-mongoose#288]
Not really an issue or a feature request, more so just a question and want to bring attention to my stack overflow question (sorry if i shouldn't be creating an issue here). https://stackoverflow.com/questions/78415974/proper-way-to-scale-ts-migrate-mongoose-migrations

**Comment by ilovepixelart** [comment]
Will answer you here.
1. To avoid issue `Cannot overwrite `User` model once compiled.`, you need this, was also provided in docs:
```TypeScript
export default models.User ?? model<IUser>('User', UserSchema)
```
2. When it comes to scalability, it's up to you how you want to scale, I simply cannot provide you example for any possible scenario you invent (as long as you follow mongoose rules you should be good)

When it comes to migrations in mongo in general experience will always be different from what you used to in SQL, because data consistency is in your hands at any given moment, and there is no enforcement of shapes you store in a given collection

When you use your models in migrations think of them as static / strict
You can use something like this https://mongoosejs.com/docs/guide.html#strict to override this behavior 
If if you want first to introduce new data and then update the model schema definition later

All ts-migrate mongoose does is running code you write, in up down functions
